Repository Quest-Finder/temvagamestre.frontend, pull requests merged in 2023-10, with the labels that each got.

#17 feat: add clerk middleware
  package-lock.json
  src/middleware.ts
  yarn.lock
Labels: enhancement

#18 Feat/add sing in component
  .env.default
  src/app/layout.tsx
  src/app/sign-in/[[...sign-in]]/page.tsx
  src/features/authentication/singIn.tsx
Labels: enhancement, GitHub, Frontend

#34 Feat/remove sing up option
  .gitignore
  package-lock.json
  src/app/layout.tsx
  src/app/page.tsx
  src/features/authentication/singIn.tsx
Labels: bug, enhancement, Frontend

#35 style: eslint rules
  .eslintrc.json
  .gitignore
  .vscode/extensions.json
  package.json
Labels: bug, documentation
