Repository Quest-Finder/temvagamestre.frontend, pull requests merged in 2024-04, with the labels that each got.

#75 Feat/step2
  src/components/ui/toggle.tsx
  src/features/social network registration/components/icon.tsx
  src/features/social network registration/components/index.ts
  src/features/social network registration/components/input-social-media.tsx
  src/features/social network registration/components/toggle-input.tsx
  src/features/social network registration/components/wrapper.tsx
  src/features/social network registration/hook/useFormSocialNetWork.tsx
  src/features/social network registration/hook/useSubmitSocialNetWokr.tsx
  src/features/social network registration/social-network-registration.tsx
  src/features/social network registration/types/social-network.d.ts
  src/features/social network registration/utils/defaul-values-social-media.ts
  src/features/social network registration/utils/get-icon-by-name.ts
  src/features/social network registration/utils/parse-validation-in-array.ts
  src/features/social network registration/utils/social-network-registration-validation.ts
Labels: Frontend

#76 Feat/step3
  src/app/(home)/page.tsx
  src/components/ui/textarea.tsx
  src/features/about-you/form-about-you.tsx
  src/features/about-you/hooks/useHookFormAboutYou.tsx
  src/features/about-you/service/useSubmitFormAboutYou.tsx
  src/features/about-you/types/validation.d.ts
  src/features/about-you/utils/default-values.ts
  src/features/about-you/utils/validation.ts
Labels: enhancement, Frontend

#77 Feat/step4
  src/components/icons/searchIcon.tsx
  src/features/address registration/address-registration.tsx
  src/features/address registration/components/input-checkbox-live-in-brazil.tsx
  src/features/address registration/components/input-city.tsx
  src/features/address registration/components/input-state.tsx
  src/features/address registration/components/options-city.tsx
  src/features/address registration/hooks/resetCityFieldWhenStateChanges.tsx
  src/features/address registration/hooks/useFormAddressRegistration.tsx
  src/features/address registration/hooks/useLocalStorageGetItem.tsx
  src/features/address registration/hooks/useResetFieldsWhenLiveInBrazil.tsx
  src/features/address registration/hooks/useSetLiveInBrazilWhenStateOrCitySet.tsx
  src/features/address registration/hooks/uselocalStorageSetItem.tsx
  src/features/address registration/service/SetErrorInFieldValue.tsx
  src/features/address registration/service/get-city-by-estate.tsx
  src/features/address registration/service/submitFormAddressRegistration.tsx
  src/features/address registration/stories/form-address.stories.tsx
  src/features/address registration/types/address-registration.d.ts
  src/features/address registration/utils/address-registration-validation.ts
  src/features/address registration/utils/defaul-values.ts
  src/features/address registration/utils/estates.ts
  src/features/address registration/utils/remove-accents.ts
  src/types/enviroment.d.ts
Labels: enhancement, Frontend

#73 Alterações fix/pageContent
  src/app/user/profile/page.tsx
  src/components/ui/card.tsx
  src/features/page-profile/box-image/components/cardWithImage.tsx
  src/features/page-profile/box-image/components/text.tsx
  src/features/page-profile/introduction/UserIntroduction.tsx
  src/features/page-profile/introduction/components/UserBio.tsx
  src/features/page-profile/introduction/components/UserSection.tsx
  src/features/page-profile/introduction/components/UserSectionTitle.tsx
  src/features/page-profile/introduction/helpers/resizeDelay.ts
  src/features/page-profile/introduction/hooks/useResize.tsx
  src/features/page-profile/introduction/introduction.stories.tsx
  src/features/page-profile/select-page/selectPage.tsx
  src/features/page-profile/user-description/components/Root.tsx
  src/features/page-profile/user-description/components/boxWithIcons.tsx
  src/features/page-profile/user-description/components/typograph.tsx
  src/features/page-profile/user-description/user-description.tsx
  src/features/page-profile/user-preference/card-category/components/List-categorys.tsx
  src/features/page-profile/user-preference/card-category/components/rpgStyle-list.tsx
  src/features/page-profile/user-preference/components/Root.tsx
  src/features/page-profile/user-preference/components/card-achievements.tsx
  src/features/page-profile/user-preference/components/card-badge.tsx
  src/features/page-profile/user-preference/components/typograph.tsx
  src/features/page-profile/user-preference/userPreferences.tsx
Labels: Frontend, high

#79 feat: created last register player form page
  src/app/registration/final/page.tsx
  src/assets/images/InsigneaDoDestino.png
  src/features/player-registration/conclusion/FormConclusion.tsx
  src/features/player-registration/conclusion/components/ConclusionBadge.tsx
  src/features/player-registration/conclusion/components/ConclusionRoot.tsx
  src/features/player-registration/conclusion/components/ConclusionText.tsx
  src/features/player-registration/conclusion/components/ConclusionTitle.tsx
  src/features/player-registration/conclusion/index.ts
Labels: enhancement
