Repository Quest-Finder/temvagamestre.frontend, pull requests merged in 2024-03, with the labels that each got.

#63 Feat/add form components shadcn
  package-lock.json
  package.json
  src/components/ui/form.tsx
  src/components/ui/input.tsx
Labels: Frontend

#64 Refactor/buttonShadcn
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/components/ui/button.tsx
  tailwind.config.js
Labels: Frontend

#66 Feat/multistep component
  src/components/icons/checkComponent.tsx
  src/components/ui/multistep.tsx
Labels: enhancement, Frontend

#67 fix: fix neutral colors problem
  tailwind.config.js
Labels: bug, Frontend, high

#70 Refactor/page user profile
  src/app/user/profile/page.tsx
  src/components/icons/discord.tsx
  src/components/icons/facebookIcon.tsx
  src/components/icons/instagram.tsx
  src/components/icons/reeditIcon.tsx
  src/components/icons/tiktok.tsx
  src/components/icons/xIcon.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/separator.tsx
  src/features/page-profile/box-image/box-image.tsx
  src/features/page-profile/box-image/components/cardWithImage.tsx
  src/features/page-profile/box-image/components/root.tsx
  src/features/page-profile/box-image/components/text.tsx
  src/features/page-profile/calendar/calendarWithForm.tsx
  src/features/page-profile/calendar/components/buttonMobile.tsx
  src/features/page-profile/calendar/components/timeOptionsHeader.tsx
  src/features/page-profile/calendar/components/typograph.tsx
  src/features/page-profile/desktop/desktopPage.tsx
  src/features/page-profile/desktop/mobile-page.tsx
  src/features/page-profile/introduction/UserIntroduction.tsx
  src/features/page-profile/introduction/components/UserBio.tsx
  src/features/page-profile/introduction/components/UserTitle.tsx
  src/features/page-profile/mobile/Mobile.tsx
  src/features/page-profile/playerProfileSection/PlayerProfileSection.tsx
  src/features/page-profile/select-page/selectPage.tsx
  src/features/page-profile/select-page/useSelectPage.tsx
  src/features/page-profile/stories/page-profile-mobile.stories.tsx
  src/features/page-profile/stories/page-profile.stories.tsx
  src/features/page-profile/user-description/components/Root.tsx
  src/features/page-profile/user-description/components/boxWithIcons.tsx
  src/features/page-profile/user-description/components/typograph.tsx
  src/features/page-profile/user-description/user-description.tsx
  src/features/page-profile/user-preference/card-category/components/List-categorys.tsx
  src/features/page-profile/user-preference/card-category/components/rpgStyle-list.tsx
  src/features/page-profile/user-preference/card-category/hooks/useRpgStyle.tsx
  src/features/page-profile/user-preference/components/Root.tsx
  src/features/page-profile/user-preference/components/card-achievements.tsx
  src/features/page-profile/user-preference/components/card-badge.tsx
  src/features/page-profile/user-preference/components/card-category.tsx
  src/features/page-profile/user-preference/components/typograph.tsx
  src/features/page-profile/user-preference/userPreferences.tsx
Labels: bug, Frontend

#71 Develop
  components.json
  package-lock.json
  package.json
  src/app/(home)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/user/profile/page.tsx
  src/components/icons/checkComponent.tsx
  src/components/icons/discord.tsx
  src/components/icons/facebookIcon.tsx
  src/components/icons/instagram.tsx
  src/components/icons/reeditIcon.tsx
  src/components/icons/tiktok.tsx
  src/components/icons/xIcon.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/multistep.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/features/page-profile/box-image/box-image.tsx
  src/features/page-profile/box-image/components/cardWithImage.tsx
  src/features/page-profile/box-image/components/root.tsx
  src/features/page-profile/box-image/components/text.tsx
  src/features/page-profile/calendar/components/typograph.tsx
  src/features/page-profile/desktop/desktopPage.tsx
  src/features/page-profile/desktop/mobile-page.tsx
  src/features/page-profile/introduction/UserIntroduction.tsx
  src/features/page-profile/introduction/components/UserTitle.tsx
  src/features/page-profile/mobile/Mobile.tsx
  src/features/page-profile/playerProfileSection/PlayerProfileSection.tsx
  src/features/page-profile/playerProfileSection/components/CustomTooltip.tsx
  src/features/page-profile/select-page/selectPage.tsx
  src/features/page-profile/select-page/useSelectPage.tsx
  src/features/page-profile/stories/page-profile-mobile.stories.tsx
  src/features/page-profile/stories/page-profile.stories.tsx
  src/features/page-profile/user-description/components/Root.tsx
  src/features/page-profile/user-description/components/boxWithIcons.tsx
  src/features/page-profile/user-description/components/typograph.tsx
  src/features/page-profile/user-description/user-description.tsx
  src/features/page-profile/user-preference/card-category/components/List-categorys.tsx
  src/features/page-profile/user-preference/card-category/components/rpgStyle-list.tsx
  src/features/page-profile/user-preference/card-category/hooks/useRpgStyle.tsx
  src/features/page-profile/user-preference/components/Root.tsx
  src/features/page-profile/user-preference/components/card-badge.tsx
  src/features/page-profile/user-preference/components/card-category.tsx
  src/features/page-profile/user-preference/components/typograph.tsx
  src/features/page-profile/user-preference/userPreferences.tsx
  tailwind.config.js
Labels: bug, enhancement, Frontend

#72 Correção de estilização na página
  src/app/user/profile/page.tsx
  src/components/ui/card.tsx
  src/features/page-profile/box-image/components/cardWithImage.tsx
  src/features/page-profile/box-image/components/text.tsx
  src/features/page-profile/introduction/UserIntroduction.tsx
  src/features/page-profile/introduction/components/UserBio.tsx
  src/features/page-profile/introduction/components/UserSection.tsx
  src/features/page-profile/introduction/components/UserSectionTitle.tsx
  src/features/page-profile/introduction/helpers/resizeDelay.ts
  src/features/page-profile/introduction/hooks/useResize.tsx
  src/features/page-profile/introduction/introduction.stories.tsx
  src/features/page-profile/select-page/selectPage.tsx
  src/features/page-profile/user-description/components/Root.tsx
  src/features/page-profile/user-description/components/boxWithIcons.tsx
  src/features/page-profile/user-description/components/typograph.tsx
  src/features/page-profile/user-description/user-description.tsx
  src/features/page-profile/user-preference/card-category/components/List-categorys.tsx
  src/features/page-profile/user-preference/card-category/components/rpgStyle-list.tsx
  src/features/page-profile/user-preference/components/Root.tsx
  src/features/page-profile/user-preference/components/card-achievements.tsx
  src/features/page-profile/user-preference/components/card-badge.tsx
  src/features/page-profile/user-preference/components/typograph.tsx
  src/features/page-profile/user-preference/userPreferences.tsx
Labels: Frontend
