Repository Quest-Finder/temvagamestre.frontend, pull requests merged in 2024-02, with the labels that each got.

#55 Fix/mock import
  src/features/page-profile/playerProfileSection/helpers/getIcon.tsx
  src/features/page-profile/playerProfileSection/stories/GraphLegend.stories.tsx
Labels: bug, Frontend

#54 refactor: I added selection to style preferences
  package-lock.json
  package.json
  src/components/ui/alert-dialog.tsx
  src/components/ui/dialog.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/features/page-profile/box-image/components/cardWithImage.tsx
  src/features/page-profile/mobile/Mobile.tsx
  src/features/page-profile/mocks/mock.ts
  src/features/page-profile/user-preference/card-category/components/List-categorys.tsx
  src/features/page-profile/user-preference/card-category/components/dialog.tsx
  src/features/page-profile/user-preference/card-category/components/root.tsx
  src/features/page-profile/user-preference/card-category/components/rpgStyle-list.tsx
  src/features/page-profile/user-preference/card-category/hooks/useRpgStyle.tsx
  src/features/page-profile/user-preference/card-category/index.tsx
  src/features/page-profile/user-preference/card-category/rpgStyle.d.ts
  src/features/page-profile/user-preference/components/card-category.tsx
  src/features/page-profile/user-preference/components/category.tsx
Labels: enhancement, Frontend

#60 feat: correção final do eslint
  package-lock.json
  src/components/ui/alert-dialog.tsx
  src/components/ui/dialog.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/features/page-profile/box-image/components/cardWithImage.tsx
  src/features/page-profile/mobile/Mobile.tsx
  src/features/page-profile/playerProfileSection/stories/GraphLegend.stories.tsx
  src/features/page-profile/user-preference/card-category/components/List-categorys.tsx
  src/features/page-profile/user-preference/card-category/components/dialog.tsx
  src/features/page-profile/user-preference/card-category/components/root.tsx
  src/features/page-profile/user-preference/card-category/components/rpgStyle-list.tsx
  src/features/page-profile/user-preference/card-category/hooks/enumRPGType.ts
  src/features/page-profile/user-preference/card-category/hooks/useRpgStyle.tsx
  src/features/page-profile/user-preference/card-category/index.tsx
  src/features/page-profile/user-preference/card-category/rpgStyle.d.ts
  src/features/page-profile/user-preference/components/card-category.tsx
  src/features/page-profile/user-preference/components/category.tsx
Labels: bug

#62 Fix/tailwindconfig
  components.json
  src/app/globals.css
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/features/page-profile/calendar/calendarWithForm.tsx
  src/features/page-profile/calendar/components/buttonMobile.tsx
  src/features/page-profile/calendar/components/timeOptionsHeader.tsx
  src/features/page-profile/calendar/components/typograph.tsx
  src/features/page-profile/introduction/components/UserBio.tsx
  src/features/page-profile/playerProfileSection/components/CustomTooltip.tsx
  src/features/page-profile/user-description/components/boxWithIcons.tsx
  src/features/page-profile/user-description/components/typograph.tsx
  src/features/page-profile/user-description/user-description.tsx
  src/features/page-profile/user-preference/components/card-achievements.tsx
  src/features/page-profile/user-preference/components/typograph.tsx
  tailwind.config.js
Labels: bug, Frontend
