Repository Quest-Finder/temvagamestre.frontend, pull requests merged in 2024-08, with the labels that each got.

#106 chore/issue-template
  .github/ISSUE_TEMPLATE/01-bug_report.yml
  .github/ISSUE_TEMPLATE/02-feature_request.yml
  .github/ISSUE_TEMPLATE/03-task.yml
  .github/ISSUE_TEMPLATE/04-documentation.yml
  .github/ISSUE_TEMPLATE/05-default_template.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, enhancement

#107 doc/readme
  README.md
Labels: documentation

#109 hotfix/pronoun-option
  src/features/register-player/player-registration/FormStepOne.tsx
Labels: bug, frontend

#105 hotfix/fix-style-bugs-on-game-style-form
  src/app/cadastro/local/page.tsx
  src/app/cadastro/redes-sociais/page.tsx
  src/features/register-player/about-you/form-about-you.tsx
  src/features/register-player/about-you/hooks/useHookFormAboutYou.tsx
  src/features/register-player/about-you/service/useSubmitFormAboutYou.tsx
  src/features/register-player/address-registration/address-registration.tsx
  src/features/register-player/address-registration/components/input-checkbox-live-in-brazil.tsx
  src/features/register-player/address-registration/components/input-city.tsx
  src/features/register-player/address-registration/components/input-state.tsx
  src/features/register-player/address-registration/components/options-city.tsx
  src/features/register-player/address-registration/hooks/resetCityFieldWhenStateChanges.tsx
  src/features/register-player/address-registration/hooks/useFormAddressRegistration.tsx
  src/features/register-player/address-registration/hooks/useLocalStorageGetItem.tsx
  src/features/register-player/address-registration/hooks/useResetFieldsWhenLiveInBrazil.tsx
  src/features/register-player/address-registration/hooks/useSetLiveInBrazilWhenStateOrCitySet.tsx
  src/features/register-player/address-registration/hooks/uselocalStorageSetItem.tsx
  src/features/register-player/address-registration/service/SetErrorInFieldValue.tsx
  src/features/register-player/address-registration/service/get-city-by-estate.tsx
  src/features/register-player/address-registration/service/submitFormAddressRegistration.tsx
  src/features/register-player/address-registration/stories/form-address.stories.tsx
  src/features/register-player/address-registration/types/address-registration.d.ts
  src/features/register-player/address-registration/utils/address-registration-validation.ts
  src/features/register-player/address-registration/utils/defaul-values.ts
  src/features/register-player/address-registration/utils/estates.ts
  src/features/register-player/address-registration/utils/remove-accents.ts
  src/features/register-player/conclusion/FormConclusion.tsx
  src/features/register-player/game-styles/FormGameStyles.tsx
  src/features/register-player/game-styles/helpers/index.ts
  src/features/register-player/game-styles/hooks/index.ts
  src/features/register-player/game-styles/hooks/useFormGameStyles.ts
  src/features/register-player/game-styles/hooks/useSubmitGameStyles.ts
  src/features/register-player/player-profile/FormPlayerProfile.tsx
  src/features/register-player/player-registration/FormStepOne.tsx
  src/features/register-player/player-registration/components/FormStepOneDateOfBirth.tsx
  src/features/register-player/player-registration/helper/index.ts
  src/features/register-player/player-registration/hooks/index.ts
  src/features/register-player/player-registration/hooks/useFormStepOne.tsx
  src/features/register-player/player-registration/hooks/useStateDateOfBirth.tsx
  src/features/register-player/player-registration/hooks/useSubmitStepOne.tsx
  src/features/register-player/social-network-registration/components/icon.tsx
  src/features/register-player/social-network-registration/components/index.ts
  src/features/register-player/social-network-registration/components/input-social-media.tsx
  src/features/register-player/social-network-registration/components/toggle-input.tsx
  src/features/register-player/social-network-registration/components/wrapper.tsx
  src/features/register-player/social-network-registration/hook/useFormSocialNetWork.tsx
  src/features/register-player/social-network-registration/hook/useSubmitSocialNetWokr.tsx
  src/features/register-player/social-network-registration/social-network-registration.tsx
  src/features/register-player/social-network-registration/types/social-network.d.ts
  src/features/register-player/social-network-registration/utils/defaul-values-social-media.ts
  src/features/register-player/social-network-registration/utils/get-icon-by-name.ts
  src/features/register-player/social-network-registration/utils/parse-validation-in-array.ts
  src/features/register-player/social-network-registration/utils/social-network-registration-validation.ts
  src/features/register-player/utils/index.ts
  src/features/register-player/utils/submitFormRegister.tsx
  src/lib/api.ts
  src/types/enviroment.d.ts
Labels: bug, frontend, high

#136 feature/player-onboarding
  src/app/(home)/page.tsx
  src/app/auth/sign-up/page.tsx
  src/app/register/onboarding/locales/pt-BR.json
  src/app/register/onboarding/page.tsx
  src/assets/branding/logo-full-white.svg
  src/assets/branding/logo-short-white.svg
  src/assets/images/onboarding-image.jpg
  src/components/ui/nav-button.tsx
  src/constants/routes.ts
  src/services/routers.ts
Labels: feature

#139 feature/interactive-validation
  src/app/auth/sign-up/@types/password.d.ts
  src/app/auth/sign-up/_components/password-requirements.tsx
  src/app/auth/sign-up/_components/sign-up-form.tsx
  src/app/auth/sign-up/_helpers/check-password-requirements.ts
  src/app/auth/sign-up/_helpers/index.ts
  src/app/auth/sign-up/_hooks/use-sign-up-form.ts
  src/app/auth/sign-up/locales/pt-BR.json
  src/components/form/form-description.tsx
Labels: feature

#140 feature/add-husky
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc
  commitlint.config.ts
  package-lock.json
  package.json
Labels: feature

#112 Fix/clerk
  .npmrc
  .nvmrc
  package-lock.json
  package.json
  src/app/globals.css
  src/constants/routes.ts
  src/middleware.ts
Labels: bug
